### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lyuguol** [gsx-ucas/QRAP#5]
Dear Shixue,

I ran into the 'QRSeq' that was developed by and would like to try to use it for RNA-seq analysis. However, I encountered the following error when installing it. Could you help to take a look at the error and show me how to solve it?

Thank you and best,

Guoliang

devtools::install_github("goushixue/QRseq", repos = NULL)
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner and repo name correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by gsx-ucas** [comment]
I am so sorry about that!
The package is still under development and the document is not updated in time, and I also changed my username and the repo name.
you can install this package by the following command:
```
devtools::install_github("gsx-ucas/QRAP")
```
By the way, there may be some bugs or function errors when using, and we would appreciate it if you could feed them back to us.
